### ISSUE TITLE
Hologram Effect

### ISSUE THREAD

**Issue by allo-** [allo-/virtual_webcam_background#11]
Add the hologram effect from https://elder.dev/posts/open-source-virtual-background/ as a filter.

**Comment by Baggypants** [comment]
You can do it with `  - "foreground": [ "stripes", [ "colorize", [ 120, 120, 255 ]], [ "change_alpha",  -80  ] ]  # hologram` and some carefully selected foreground and background.

[example](https://mstdn.social/web/statuses/104964365808801948)

**Comment by allo-** [comment]
We already have the full plugin almost ready to merge, see #39. I am currently waiting on @aguinet to add a few minor improvements.

**Comment by aguinet** [comment]
Hello!

Sorry I completely missed your answers.. I will get back to this asap this weekend!
