### ISSUE TITLE
KeyError Frame when setting single_color

### ISSUE THREAD

**Issue by schwab** [allo-/virtual_webcam_background#18]
What's the proper syntax for setting up a background fill color of green (as in setting up a virtual green screen to pipe to other apps)?  

I've tried a few variations like : 
background_filters: ["grayscale",["single_color",[0, 255, 0] ]]
background_filters: ["grayscale",["single_color",0, 255, 0 ]]
background_filters: [["single_color",{r:0, g:255, b:0]]

But all of them fail with : 
```Reloading config.
Loading model...
done.
Traceback (most recent call last):
  File "./virtual_webcam.py", line 264, in <module>
    mainloop()
  File "./virtual_webcam.py", line 188, in mainloop
    filters.get_filters(config.get("background_filters", [])))
  File "/mnt/raid3tb/installs/virtual_webcam_background/filters/__init__.py", line 53, in apply_filters
    frame = image_filter(frame=frame)
  File "/mnt/raid3tb/installs/virtual_webcam_background/filters/__init__.py", line 45, in filter_with_parameters
    return _image_filter(*args, **kwargs)
  File "/mnt/raid3tb/installs/virtual_webcam_background/filters/color.py", line 8, in single_color
    return color_filter(frame, r, g, b)
  File "/mnt/raid3tb/installs/virtual_webcam_background/filters/color.py", line 11, in color_filter
    frame = kwargs['frame']
KeyError: 'frame'

```

Note: grayscale works OK by itself.

**Comment by allo-** [comment]
Use a green background image for now.

First you hit a bug. I am making the filters more flexible (so the program can get additional information about the frame without breaking old filters) and `single_color` using `color_filter` with the old syntax.

But second you are misunderstanding `single_color`, which may have no good name for what it does. The function converts the image to grayscale and then tints it with the given color, so you would not get a flat green color, but an green image of your background.

These lines should do the same:
```
 background_filters: [["single_color", 0, 255, 0]]
 background_filters: ["grayscale", ["color_filter", 0, 255, 0]]
```

The difference to `color_filter` itself is, that color filter return the green channel, i.e., black for parts of the image that only contain red objects, and `single_color` colors the grayscale image.

I may rename `single_color` to `tint` or something similar and add a `single_color` function like you expected it later.

The syntax in your config is almost correct. The last line should have a `}`.

**Comment by schwab** [comment]
Setting a simple background image like this worked.
```
background_image: "green.png"
```
It was a little tricky to get the other settings correct to remove the green outline and not chop off too much in the process, but I think I got it pretty well dialed in now.  

Thanks You.

**Comment by allo-** [comment]
I reopen the issue until the exception is fixed.

**Comment by allo-** [comment]
@schwab In what other apps do you pipe the output?
I am wonder if you're missing features that possibly could be added to this program as well.

**Comment by allo-** [comment]
Implementing a `solid_color` filter would not make sense for most use cases, as it can for example only be applied to the background, when a background image is set.

Here it would be more useful to either implement `background_color` as alternative to `background_image` or when the filter infrastructure is extended as in #14 (not sure if I want to do this) then `background_image` and `solid_color` could both be implemented as filters (replacing the webcam image).

Currently solid color would have one use, that is to be an overlay to hide the foreground. There are probably not many people who would use this, though.

**Comment by schwab** [comment]
Currently I use the output off this as an input to OBS studio.  This allows me to add a color key and replaced the background with video as well as easily switch between scenes etc.  Then OBS is setup to output to another loopback which appears as a web cam to slack, hangouts or zoom.

**Comment by allo-** [comment]
You are using #00ff00 as chroma key, aren't you?

Maybe I should add a green screen image by default for that use-case.

**Comment by allo-** [comment]
@schwab I added a `solid_color` filter that can be used to fill the background with a single color.

As documented in the readme, you will need to change the config for the latest changes, but this should be rather easy. You probably need these layers:

```
layers:
  - empty: [["solid_color", 0.0, 255.0, 0.0]]
  - foreground: []
```
