### ISSUE TITLE
Low FPS

### ISSUE THREAD

**Issue by QuillzLouis** [allo-/virtual_webcam_background#27]
Testing this on Discord the frame rate was really low so I ran it through webcam test and got this result, any reason why/solution to fix?
![image](https://user-images.githubusercontent.com/16400169/82159267-edbe5400-9884-11ea-911c-2683fca9b81f.png)

**Comment by allo-** [comment]
There are several parts that affect the performance. In #20 is the bug for ideas and #12 is the bug for collecting (good) configurations.

I still think it is good to debug *your* issue, as it may help to identify the bottlenecks, before optimizing something else.

- How many FPS can your camera provide in the best case? I had resolutions where my camera was the limiting factor.
- Are you using CPU or GPU?
- What CPU are you using?
- Does it have different framerates in different programs?
- What FPS does the loopback achive when you use it with other programs? Try something like `ffmpeg -re -i some_movie.mp4 -f v4l2 /dev/videoX`.
- Please post your layers config, what filters are you using?

I think I can create later a branch with some benchmark code. For just testing the camera operations and the model you can try to use only the input layer:

    layers:
        - "input": []

Parameters to tune:

- Use another model. `resnet` is slow, `mobilenet` (default) is faster, multiplier `0.5` is faster than `1.0`, etc.
- try to reduce `internal_resolution` (`0.0` to `1.0`)
- When the (almost) empty layers are fast, have a look which filters are slow (some filters *are* slow)

You can try an easy benchmark you can use `time.time()` like this:

https://github.com/allo-/virtual_webcam_background/issues/20#issuecomment-621318347

I think I can create a branch that uses a simple benchmark like this at different places in the code for testing purposes.

**Comment by allo-** [comment]
I close here now, because of not getting feedback.
Please post concrete Ideas for performance optimization in #20 and general feedback on the performance of different configurations in #12 and the corresponding wiki article.
