### ISSUE TITLE
Request: Any chance to make this a gui instead of a command line utility?

### ISSUE THREAD

**Issue by tdbe** [allo-/virtual_webcam_background#76]
When you just want to put this on a new machine, you just want to doubleclick one file, and the thing to open up and run with a default setting. :)

So batching this all up in a portable package for win, linux etc, would be great chore alleviator.
A tray icon would be immensely useful as well to know if it's on and check the settings.

[edit] wait, is this even fully installable on windows? looking at v4l2loopback....?

**Comment by allo-** [comment]
There is a project, that allows graphical configuration, see #4.
When someone is willing to package it with a gui with a tray icon and so on, I am willing to assist how to couple it.

Drivers: Currently supported are v4l2loopback and akvcam (both Linux drivers).
But anything that you get to work with `pyfakewebcam` can be used. Input via opencv should work on all platforms, so you only need to investigate which virtual webcam drivers are available on other platforms and how easy or comlicated it is to send frames to the virtual device.

I close here for the GUI part as it is covered in #4.
When you like to contribute to packaging or supporting other drivers, feel free to open another issue, if there isn't one yet.
